const path = require('path');

module.exports = {
  apps: [
    {
      name: 'app.ekklesia.vote',
      script: path.resolve(__dirname, 'server.js'),
      watch: true,
      ignore_watch: [
        'node_modules',
        'logs',
        'backup',
        'scripts',
        'public',
        'preprod-logs',
        'mainnet-logs',
      ],
      watch_options: {
        followSymlinks: false,
        usePolling: true,
      },
      exec_mode: 'cluster',
      instances: 'max',
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'mainnet',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: path.resolve(__dirname, 'logs/server-error.log'),
      out_file: path.resolve(__dirname, 'logs/server-output.log'),
      combine_logs: true,
      merge_logs: true,
      time: true,
      max_logs: '30d',
      log_size: '50M',
    },
    // Backup job - runs in both environments
    {
      name: 'app.ekklesia.vote-backup',
      script: path.resolve(__dirname, 'backup/backup.js'),
      watch: false,
      autorestart: false,
      cron_restart: '0 */1 * * *',
      env: {
        NODE_ENV: 'mainnet',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: path.resolve(__dirname, 'logs/backup-error.log'),
      out_file: path.resolve(__dirname, 'logs/backup-output.log'),
      combine_logs: true,
      merge_logs: true,
      time: true,
      max_logs: '30d',
      log_size: '10M',
    },
    // Ten-minute job
    {
      name: 'app.ekklesia.vote-cron10min',
      script: path.resolve(__dirname, 'crons/10min.js'),
      watch: false,
      autorestart: false,
      cron_restart: '*/10 * * * *',
      env: {
        NODE_ENV: 'mainnet',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: path.resolve(__dirname, 'logs/cron10min-error.log'),
      out_file: path.resolve(__dirname, 'logs/cron10min-output.log'),
      combine_logs: true,
      merge_logs: true,
      time: true,
      max_logs: '30d',
      log_size: '10M',
    },
    // Hourly job
    {
      name: 'app.ekklesia.vote-cron1h',
      script: path.resolve(__dirname, 'crons/1h.js'),
      watch: false,
      autorestart: false,
      cron_restart: '0 * * * *',
      env: {
        NODE_ENV: 'mainnet',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: path.resolve(__dirname, 'logs/cron1h-error.log'),
      out_file: path.resolve(__dirname, 'logs/cron1h-output.log'),
      combine_logs: true,
      merge_logs: true,
      time: true,
      max_logs: '30d',
      log_size: '10M',
    },
  ],
};
